directory: ~/music
library: ~/music/.beets/library.db

original_date: yes
import:
  move: yes
  log: ~/music/.beets/log.txt
  languages: en
  group_albums: yes
  bell: yes

ui:
  color: yes

paths:
  default: $albumartist/$album%aunique{}/$track $title
  singleton: Non-Album/$artist/$title
  comp: Compilations/$album%aunique{}/$track $title

plugins: replaygain mbsync lastgenre fetchart follow smartplaylist mpdupdate

replaygain:
  backend: gstreamer

follow:
    email: brxck@protonmail.com
    password: yNAbihPZaM4ia6do
    userid: fbgodusfpfbt5jd3jee9x6uoh6ce9j
    auto: yes
    
smartplaylist:
  relative_to: ~/music
  playlist_dir: ~/.playlists

  playlists:
    - name: all.m3u
      query: ''
